Update to Rust Nightly 2023-06-02 (stable 1.70.0)
hacspec/hacspec-v2 pull request #144
Opened 2023-06-13 16:19 UTC by W95Psp

2023-06-13 17:07 UTC, franziskuskiefer requested changes
The nightly version in the readme needs updating (or just point to the toolchain toml so we don't need to keep them in sync).

The diagnostics crate needs an `extern crate rustc_driver;` to fix the crate (I pushed this change on your branch here).

2023-06-14 07:59 UTC, W95Psp commented
There are some issues with the macro information recovering phase :(
Rustc now wraps surface ASTs in a `Steal` structure, and we're facing again stealing issues (but now only for the surface AST)

2023-06-14 11:08 UTC, franziskuskiefer reviewed
The changes itself look good to me but you are re-introducing the stealing bug.

2023-06-14 12:33 UTC, W95Psp commented on frontend/exporter/src/all.rs
> +// fn resolve_trait<'tcx, S: BaseState<'tcx>>(trait_ref: rustc_middle::ty::TraitRef<'tcx>, s: &S) {
I left the function `resolve_trait` there finally, but commented it out, and renamed it `_resolve_trait`.
For now we don't use it, but we will need it soon for impl resolution (#20)

2023-06-14 14:38 UTC, franziskuskiefer approved these changes
:shipit: 
bors r+

2023-06-14 14:47 UTC, W95Psp commented
bors r+

2023-06-14 15:31 UTC, merged