Cleanup frontend
hacspec/hacspec-v2 pull request #201
Opened 2023-07-12 12:49 UTC by W95Psp

2023-07-12 14:46 UTC, franziskuskiefer requested changes
I didn't look at the code yet but this doesn't actually terminate when running on a relatively small crate.

2023-07-12 15:33 UTC, W95Psp commented
uh, gonna debug that

2023-07-17 08:51 UTC, W95Psp commented
I added logging at various places.
I don't observe non-termination on my side though, I tried a few things, including Hax itself and openmls (that fails at some point).

2023-08-02 12:34 UTC, franziskuskiefer approved these changes

2023-08-02 13:09 UTC, merged